volumes:
  postgres:
  minio:

services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:3.6.1
    ports:
      - "2333:2333"
    volumes:
      - "./config/lavalink/application.yml:/opt/Lavalink/application.yml:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "yuri69"
      POSTGRES_USER: "yuri69"
      POSTGRES_DB: "yuri69"
    restart: unless-stopped

  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio:/data"
    environment:
      MINIO_ACCESS_KEY: "yuri69"
      MINIO_SECRET_KEY: "yuri69_secret_key"
    command: server /data --console-address :9001
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18080:8080
