name: Releases CD

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "^1.18"
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: task build --force
      - name: Rename Binary
        env:
          FNAME: ./bin/yuri-${{ matrix.goos }}-${{ matrix.goarch }}
        run: mv ./bin/yuri ${{ env.FNAME }}
      - name: Rename Windows Binary
        if: ${{ matrix.goos == 'windows' }}
        env:
          FNAME: ./bin/yuri-${{ matrix.goos }}-${{ matrix.goarch }}
        run: mv ${{ env.FNAME }} ${{ env.FNAME }}.exe
      - name: Upload Artifcats
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./bin/
          retention-days: 1

  deploy:
    name: Deploy to Releases
    runs-on: ubuntu-latest
    needs:
      - 'build_artifacts'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve backend binaries
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: bin/
      - name: Inject Version into Changelog
        run: |-
          sed -i "s/\[VERSION\]/$(git describe --tags --abbrev=0)/g" CHANGELOG.md
      - name: Set up Hub
        run: |-
          sudo snap install hub --classic
      - name: Deploy to Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "hub release create
          $(ls ./bin -1 | xargs -I % printf '-a ./bin/% ')
          -F ./CHANGELOG.md
          $(git describe --tags --abbrev=0)"
